<a href="https://colab.research.google.com/github/95871abhinandankumar/95871abhinandankumar/blob/main/assignment7_AND_logicGATE_perceptron_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [48]:
import numpy as np


In [49]:
def predicted(w, x):
  if np.dot(w, x) >= 0:
    return 1
  else:
    return 0

In [50]:
def accuaracy(dataset, w):
  count = 0
  for i in range(len(dataset)):
    if predicted(w, dataset[i][0:-1]) == dataset[i][-1]:
      count += 1
  return count/len(dataset) 


In [51]:
def perceptron_model(dataset, w, epoch):

  for _ in range(epoch):
    for i in range(len(dataset)-1):
      print(i)
      print(dataset[i][0:-1])
      print(w)
      while predicted(w, dataset[i][0:-1]) != dataset[i][-1]:
        
        if predicted(w, dataset[i][0:-1]) < 0 and dataset[i][-1] == 1:
          w = np.add(w, dataset[i][0:-1])
        elif predicted(w, dataset[i][0:-1]) >= 0 and dataset[i][-1] == 0:
          w = np.subtract(w, dataset[i][0:-1])
  return w

In [52]:
dataset = [[1,0,0,0], [1,0,1,0],[1,1,0,0],[1,1,1,1]]

dataset = np.array(dataset)
print(dataset)

[[1 0 0 0]
 [1 0 1 0]
 [1 1 0 0]
 [1 1 1 1]]


In [53]:
w = np.array([0.1, 0.1, 0.1])

w = perceptron_model(dataset, w, 1)

print(accuaracy(dataset, w))

0
[1 0 0]
[0.1 0.1 0.1]
1
[1 0 1]
[-0.9  0.1  0.1]
2
[1 1 0]
[-0.9  0.1  0.1]
0.75
