<a href="https://colab.research.google.com/github/95871abhinandankumar/Machine-learning/blob/main/k_mediods_evalutionLab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd # reading all required header files
import numpy as np
import random
import operator
import math
import matplotlib.pyplot as plt 
from scipy.stats import multivariate_normal 
from sklearn.datasets import load_iris

In [ ]:
iris = load_iris()
df = pd.DataFrame(iris.data)

In [ ]:
n = len(df)
k = 3
d = 4
m = 2
MAX_ITERS = 300

In [ ]:
def initializeMembershipWeights():
  """
  membership_mat = []
  for i in range(n):
    wts = []
    sum=0;
    for j in range(k):
      weight = np.random.random_integers(1,10)
      wts.append(weight)
      sum = sum + weight
    weights = [w/sum for w in wts]
    membership_mat.append(weights)
    print(membership_mat)

    """
  weight = np.random.dirichlet(np.ones(k),n)
  weight_arr = np.array(weight)
  return weight_arr

In [ ]:
def computeCentroids(weight_arr):
  C = []
  for i in range(k):
    weight_sum = np.power(weight_arr[:,i],m).sum()
    Cj = []
    for x in range(d):
      numerator = ( df.iloc[:,x].values * np.power(weight_arr[:,i],m)).sum()
      c_val = numerator/weight_sum;
      Cj.append(c_val)
    C.append(Cj)
  return C

In [ ]:
def updateWeights(weight_arr,C):
  denom = np.zeros(n)
  for i in range(k):
    dist = (df.iloc[:,:].values - C[i])**2
    dist = np.sum(dist, axis=1)
    dist = np.sqrt(dist)
    denom  = denom + np.power(1/dist,1/(m-1))

  for i in range(k):
    dist = (df.iloc[:,:].values - C[i])**2
    dist = np.sum(dist, axis=1)
    dist = np.sqrt(dist)
    weight_arr[:,i] = np.divide(np.power(1/dist,1/(m-1)),denom)
  return weight_arr

In [ ]:
def FuzzyMeansAlgorithm():
  weight_arr = initializeMembershipWeights()
  for z in range(MAX_ITERS):
    C = computeCentroids(weight_arr)
    updateWeights(weight_arr,C)

  return (weight_arr,C)

In [ ]:

final_weights,Centers = FuzzyMeansAlgorithm()
print(final_weights)

[[0.06926416 0.05508431 0.87565152]
 [0.10941919 0.08631576 0.80426505]
 [0.11258863 0.08976111 0.79765025]
 [0.12235434 0.09655046 0.7810952 ]
 [0.08004637 0.06386282 0.85609081]
 [0.14591663 0.11544308 0.73864029]
 [0.11077288 0.08821102 0.80101609]
 [0.04584078 0.03618375 0.91797547]
 [0.16194329 0.12869765 0.70935906]
 [0.09554294 0.07519445 0.82926261]
 [0.11614567 0.0924601  0.79139423]
 [0.07014415 0.05518611 0.87466973]
 [0.1200181  0.09496841 0.78501349]
 [0.17249615 0.13954629 0.68795756]
 [0.1885068  0.15459086 0.65690234]
 [0.21129527 0.17341915 0.61528559]
 [0.1460071  0.11795797 0.73603493]
 [0.06497931 0.05159599 0.88342471]
 [0.1698304  0.13443393 0.69573567]
 [0.1030587  0.08216894 0.81477237]
 [0.09775562 0.07616274 0.82608165]
 [0.08800966 0.06983227 0.84215808]
 [0.14637076 0.11934928 0.73427996]
 [0.06455815 0.04989003 0.88555182]
 [0.10095185 0.07807467 0.82097348]
 [0.0995177  0.07748842 0.82299388]
 [0.0309901  0.02423396 0.94477594]
 [0.06513581 0.05150349 0.88

In [ ]:
labels = [0  for _ in range(len(df))]

for i in range(len(df)):
  labels[i] = final_weights[i].argmax()

print(np.array(labels))

[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 1 1 1
 1 1 0 1 1 1 1 1 0 1 0 1 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1
 1 1]


In [ ]:
def calculate_SSE(datapoints, centroids, lebels):
  sse = 0
  for i in range(len(lebels)):
    cluster = lebels[i]
    sse += np.sum(np.square(np.subtract(datapoints[i], centroids[cluster])))
  return sse

In [ ]:
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import MinMaxScaler

In [ ]:
silhouette_avg = silhouette_score(df.to_numpy(), labels)

print("Fuzzy C-means algorithm analysis for Iris dataset ...........")
print("For no of clusters =", 3, " The average silhouette_score is :", silhouette_avg)
print("For no of clusters =", 3, " The SSE index is :", calculate_SSE(df.to_numpy(), Centers, labels))

Fuzzy C-means algorithm analysis for Iris dataset ...........
For no of clusters = 3  The average silhouette_score is : 0.5270101525021645
For no of clusters = 3  The SSE index is : 97.43016759613728


In [ ]:
kmeans = KMeans(n_clusters = 3, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
y_kmeans = kmeans.fit_predict(df.to_numpy())

In [ ]:
silhouette_avg = silhouette_score(df.to_numpy(), y_kmeans)

print("K-mean algorithm analysis for Iris dataset ...........")  
print("For no of clusters =", 3, " The average silhouette_score is :", silhouette_avg)
print("For no of clusters =", 3, " The average silhouette_score is :", kmeans.inertia_)

K-mean algorithm analysis for Iris dataset ...........
For no of clusters = 3  The average silhouette_score is : 0.5528190123564091
For no of clusters = 3  The average silhouette_score is : 78.85144142614601
