<a href="https://colab.research.google.com/github/95871abhinandankumar/Machine-learning/blob/main/k_mediod.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from sklearn.datasets import load_wine
wine_data = load_wine()
print(wine_data)

{'data': array([[1.423e+01, 1.710e+00, 2.430e+00, ..., 1.040e+00, 3.920e+00,
        1.065e+03],
       [1.320e+01, 1.780e+00, 2.140e+00, ..., 1.050e+00, 3.400e+00,
        1.050e+03],
       [1.316e+01, 2.360e+00, 2.670e+00, ..., 1.030e+00, 3.170e+00,
        1.185e+03],
       ...,
       [1.327e+01, 4.280e+00, 2.260e+00, ..., 5.900e-01, 1.560e+00,
        8.350e+02],
       [1.317e+01, 2.590e+00, 2.370e+00, ..., 6.000e-01, 1.620e+00,
        8.400e+02],
       [1.413e+01, 4.100e+00, 2.740e+00, ..., 6.100e-01, 1.600e+00,
        5.600e+02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
 

In [2]:
import pandas as pd
df = pd.DataFrame(wine_data.data,columns=[wine_data.feature_names])
df['target'] = wine_data.target

print(df.head())
print(wine_data.feature_names)

  alcohol malic_acid   ash  ... od280/od315_of_diluted_wines proline target
0   14.23       1.71  2.43  ...                         3.92  1065.0      0
1   13.20       1.78  2.14  ...                         3.40  1050.0      0
2   13.16       2.36  2.67  ...                         3.17  1185.0      0
3   14.37       1.95  2.50  ...                         3.45  1480.0      0
4   13.24       2.59  2.87  ...                         2.93   735.0      0

[5 rows x 14 columns]
['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']


In [3]:
from sklearn.preprocessing import MinMaxScaler
scaling = MinMaxScaler()
samples = scaling.fit_transform(df[df.columns])
df = pd.DataFrame(samples)

print(df.head())

         0         1         2         3   ...        10        11        12   13
0  0.842105  0.191700  0.572193  0.257732  ...  0.455285  0.970696  0.561341  0.0
1  0.571053  0.205534  0.417112  0.030928  ...  0.463415  0.780220  0.550642  0.0
2  0.560526  0.320158  0.700535  0.412371  ...  0.447154  0.695971  0.646933  0.0
3  0.878947  0.239130  0.609626  0.319588  ...  0.308943  0.798535  0.857347  0.0
4  0.581579  0.365613  0.807487  0.536082  ...  0.455285  0.608059  0.325963  0.0

[5 rows x 14 columns]


In [4]:
dataframe = df.iloc[: , :-1]
print(dataframe)

           0         1         2   ...        10        11        12
0    0.842105  0.191700  0.572193  ...  0.455285  0.970696  0.561341
1    0.571053  0.205534  0.417112  ...  0.463415  0.780220  0.550642
2    0.560526  0.320158  0.700535  ...  0.447154  0.695971  0.646933
3    0.878947  0.239130  0.609626  ...  0.308943  0.798535  0.857347
4    0.581579  0.365613  0.807487  ...  0.455285  0.608059  0.325963
..        ...       ...       ...  ...       ...       ...       ...
173  0.705263  0.970356  0.582888  ...  0.130081  0.172161  0.329529
174  0.623684  0.626482  0.598930  ...  0.178862  0.106227  0.336662
175  0.589474  0.699605  0.481283  ...  0.089431  0.106227  0.397290
176  0.563158  0.365613  0.540107  ...  0.097561  0.128205  0.400856
177  0.815789  0.664032  0.737968  ...  0.105691  0.120879  0.201141

[178 rows x 13 columns]


In [5]:
dataframe.columns =['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium', 'total_phenols', 'flavanoids', 'nonflavanoid_phenols', 'proanthocyanins', 'color_intensity', 'hue', 'od280/od315_of_diluted_wines', 'proline']

print(dataframe)

      alcohol  malic_acid  ...  od280/od315_of_diluted_wines   proline
0    0.842105    0.191700  ...                      0.970696  0.561341
1    0.571053    0.205534  ...                      0.780220  0.550642
2    0.560526    0.320158  ...                      0.695971  0.646933
3    0.878947    0.239130  ...                      0.798535  0.857347
4    0.581579    0.365613  ...                      0.608059  0.325963
..        ...         ...  ...                           ...       ...
173  0.705263    0.970356  ...                      0.172161  0.329529
174  0.623684    0.626482  ...                      0.106227  0.336662
175  0.589474    0.699605  ...                      0.106227  0.397290
176  0.563158    0.365613  ...                      0.128205  0.400856
177  0.815789    0.664032  ...                      0.120879  0.201141

[178 rows x 13 columns]


In [6]:
datapoints = dataframe.to_numpy()
print(datapoints)

[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]


In [7]:
import numpy as np

def calculate_SSE(datapoints, mediods, clusters):
  sse = 0
  for i in range(len(clusters)):
    cluster = clusters[i]
    sse += np.sum(np.square(np.subtract(datapoints[i], mediods[cluster])))
  return sse



In [8]:
def euclidean_distance(x1, x2):
  return np.sum(np.square(np.subtract(x1, x2)))


In [9]:
def update_cluster(datapoints, mediods):
  clusters = [ 0 for i in range(len(datapoints))]

  for i in range(len(datapoints)):
    min = 10000
    min_index = -1
    for j in range(len(mediods)):
      dist = euclidean_distance(datapoints[i], mediods[j])
      if dist < min:
        min = dist
        min_index = j
        clusters[i] = j
  return clusters


In [10]:
def swapping_cost(datapoints, mediods):
  clusters = update_cluster(datapoints, mediods)
  return calculate_SSE(datapoints, mediods, clusters)

In [11]:
def select_mediod_random(datapoints, k):
  from numpy.random import choice
  from numpy.random import seed

  seed(1)
  samples = choice(len(datapoints), size=k, replace=False)
  return datapoints[samples, :]

In [15]:
def k_mediods(datapoints, k, iterations):
  mediods = select_mediod_random(datapoints, k)
  clusters = list()

  for _ in range(iterations):
    clusters = update_cluster(datapoints, mediods)
    old_sse = calculate_SSE(datapoints, mediods, clusters)

    for i in range(len(datapoints)):

      for j in range(k):
        new_mediods = mediods.copy()
        new_mediods[j] = datapoints[i]
        new_sse = swapping_cost(datapoints, new_mediods)

        # print(clusters)

        if new_sse < old_sse :
          clusters = update_cluster(datapoints, new_mediods)
          # print("changing mediods....")
          mediods = new_mediods
          break;
  return clusters, mediods



        



In [23]:
clusters, mediods = k_mediods(datapoints, 2, 10)
print(clusters)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [24]:
print(mediods)

[[0.60263158 0.49407115 0.54545455 0.56185567 0.23913043 0.32758621
  0.08860759 0.60377358 0.26498423 0.60921502 0.05691057 0.12820513
  0.26533524]
 [0.44473684 0.21146245 0.44919786 0.42268041 0.17391304 0.42068966
  0.46202532 0.24528302 0.42902208 0.22354949 0.55284553 0.68498168
  0.31098431]]


In [25]:
from sklearn.cluster import KMeans 
from sklearn.metrics import silhouette_score

In [27]:
silhouette_avg = silhouette_score(datapoints, clusters)
  
print("For no of clusters =", 2, " The average silhouette_score is :", silhouette_avg)

For no of clusters = 2  The average silhouette_score is : 0.3009497526608838


In [30]:
kmeans = KMeans(n_clusters = 2, init = 'k-means++', max_iter = 300, n_init = 10, random_state = 0)
y_kmeans = kmeans.fit_predict(datapoints)

In [31]:
silhouette_avg = silhouette_score(datapoints, y_kmeans)
  
print("For no of clusters =", 2, " The average silhouette_score is :", silhouette_avg)

For no of clusters = 2  The average silhouette_score is : 0.2987221815974774
