<a href="https://colab.research.google.com/github/95871abhinandankumar/Machine-learning/blob/main/ML_Assignment_6_(Logistic_Regression)_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/codePerfectPlus/Logistic_Regression_From_Scratch/blob/master/IRIS%20Logistic%20Regression%20From%20Scratch.ipynb

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import math
from sklearn.model_selection import train_test_split

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()

In [ ]:
print("The dictonary keys are associated with data:\n", iris.keys())
print("-"*100)
print("Data:\n", iris['data'])
print("-"*100)
print("Name of the features (Independent features): \n", iris['feature_names'])
print("-"*100)
print("Name of the dependent features: ", iris['target_names'])
print("-"*100)

The dictonary keys are associated with data:
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])
----------------------------------------------------------------------------------------------------
Data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [

# 1. Pre-process the data to use only 2 classes (Iris-Setosa and Iris-Versicolour)

In [ ]:
y_actual = iris['target']
y_actual = list(y_actual)
counter_setosa = 0
counter_versicolor = 0
counter_virginica = 0
for i in range(0,len(y_actual)):
  if(y_actual[i]==0):
    counter_setosa = counter_setosa  + 1 
  if(y_actual[i]==1):
    counter_versicolor = counter_versicolor + 1
  if(y_actual[i]==2):
    counter_virginica = counter_virginica + 1
print("Total no of patterns in setosa class",counter_setosa)
print("Total no of patterns in setosa class",counter_versicolor)
print("Total no of patterns in setosa class",counter_virginica)
# take only first 100 patterns
for i in range(0,50):
  y_actual.remove(2)
# covert it to an numpy array 
y_actual = np.array(y_actual)
print(y_actual.shape[0])

Total no of patterns in setosa class 50
Total no of patterns in setosa class 50
Total no of patterns in setosa class 50
100


In [ ]:
# take only first 100 patterns for the binary classification 
features = list(iris['data'])
print(len(features))
del features[100:]
print(len(features))
features = np.array(features)
print("No of the feature vectors: %d"%features.shape[1])
print("No of the Patterns: %d"%features.shape[0])

150
100
No of the feature vectors: 4
No of the Patterns: 100


# 2. Divide the dataset into train, validation and test with the dataset division ratio of your choice.

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(features)
features = scaler.transform(features)

In [ ]:
# Train test validation
from sklearn.model_selection import train_test_split
import random
# train(70%), validation (10%), and test(20%)
X_train, X_test, y_train, y_test = train_test_split(features,y_actual , test_size=0.3, random_state=random.randint(30,100))
X_test, X_validation, y_test, y_validation = train_test_split(X_test, y_test, test_size=0.14, random_state=random.randint(30,100))
print("Size of the train dataset:",X_train.shape)
print("Size of the validation dataset:",X_validation.shape)
print("Size of the test dataset:",X_test.shape)

Size of the train dataset: (70, 4)
Size of the validation dataset: (5, 4)
Size of the test dataset: (25, 4)


# 3. Hyperparameter tuning on the validation set is required to be done.

3.1. Sigmoid function

In [ ]:
def sigmoid(x):
  z = 1/(1 + np.exp(-x))
  return z

3.2. Gradient Decent Algorithem

In [ ]:
import numpy as np
import random
def gradient_descent(alpha, x, y, roh = 0.0001, max_iter=10):
    converged = False
    iter = 0
    m = x.shape[0]
    n = x.shape[1]
    # Initial Weights
    weight = np.ones(n+1)
    hypo = np.ones(m)
    random.seed(10) # for the same weight intialization
    for i in range(0, n+1):
      weight[i] = random.uniform(-0.3, 0.3)
    # calculate the hypothesis value with the intial weights
    k = 0
    for i in range(0, m):
      rest = 0 
      for j in range(1, n+1):
        rest = rest + weight[j]*x[i][j-1]
      hypo[i] = 1*weight[0] + rest
      hypo[i] = sigmoid(hypo[i]) # call sigmoid function for the hypothesis
    # implement log loss function of the error
    temp_sum = 0
    for i in range(0, x.shape[0]):
      temp_sum = temp_sum + ((y[i]*math.log(hypo[i])) + (1-y[i])*math.log(hypo[i]))
    log_loss = -(1/x.shape[0])*temp_sum
    while not converged:
        error = 0
        # Update the weight
        hypothesis = 0
        temp_out = 0
        for i in range(0, m):
          rest = 0 
          for j in range(1, n+1):
            rest = rest + weight[j]*x[i][j-1]
          hypo[i] = 1*weight[0] + rest
          hypo[i] = sigmoid(hypo[i])
        for i in range(0, m):
          weight[0] = (hypo[i] - y[i])*1
        for i in range(0, m): # fix the row
          hypothesis = 0
          for j in range(0, n+1): # fix the column
            hypothesis = hypothesis + weight[j+1]*x[i][j] # hypothesis calculation
          if()
          temp_out = temp_out + (weight[0] + hypothesis - y[j])*1 # as xi,0 = 1
        my_sum[0] = temp_out # for the weight 0
        # for rest of the weights
        for k in range(1, n+1):
          hypothesis = weight[0]
          temp_out = 0
          for i in range(0, m): # vary the row
            for j in range(0, n):
              hypothesis = hypothesis + weight[j+1]*x[i][j]
            temp_out = temp_out + (weight[1] + temp_in - y[j])*x[i][k]
          my_sum[k] = temp_out
        # weight updatation
        for j in range(0,n+1):
          weight[j] = weight[j] - (alpha/m) * my_sum[j]
        return weight
        # Calculate the Mean Squared Error
        for i in range(0,m): # vary the row
          for j in range(0,x.shape[1]):
            temp_in = temp_in + weight[j+1]*x[i][j]
          error = error + (weight[0] + temp_in - y[i])**2 # total error
        print(error)
        if abs(total_error-error) <= ep:
            print(total_error)
            print(error)
            print('Converged, iterations: ', iter, '!!!')
            converged = True
        total_error = error  # update error 
        iter += 1  # update iter
        if iter == max_iter:
            print('Max interactions exceeded!')
            converged = True
    return weight, error

In [ ]:
shyam = gradient_descent(0.01, X_train, y_train, roh=0.00001, max_iter=10)
print(shyam)

IndexError: ignored

In [ ]:
y_test = [1, 2, 3]
y = y_test[0] # y = 1
print(y[0]) # this line will fail

TypeError: ignored

In [ ]:
alpha = [ 0.1, 0.001, 0.0001, 0.5, 1.0]
mse = np.ones(5)
weight = np.ones(14)
for i in range(5):
  weight,mse[i] = gradient_descent(alpha[i], X_train, y_train, ep=0, max_iter=1000)